project:
  type: website
  output-dir: docs
  
website:
  title: "1website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



