project:
  type: website
  output-dir: docs
  
website:
  title: "Zijun (Frank) Meng "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ZijunResume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



